### ISSUE TITLE
"Top lines" may be unclear

### ISSUE THREAD

**Issue by alphapapa** [trevorpogue/topspace#20]
Hi,

FYI, I wasn't sure what this package did until I saw the demo GIF, because I didn't know what "top lines" meant.  You may want to explain that differently in the description.  :)

**Comment by trevorpogue** [comment]
Hi, thanks for the feedback. Do you have any ideas for wording that might be more clear? Here are some alternatives I can think of: 

scroll down and recenter line 1 ...
scroll down and recenter to line 1 ...
scroll down and recenter lines 1+ ...
scroll down and recenter lines 1-n ...
scroll down and recenter the first lines of a buffer ...

**Comment by alphapapa** [comment]
I think the key is that this package allows the user to do something that Emacs doesn't normally permit.  So I would go with a more plain-language description, maybe something like: "This package allows the user to display the first line of the buffer with blank lines above it, below the first line of the window.  In other words, the first line of the buffer can now be displayed in the center of the window, as if it weren't the first line."

**Comment by trevorpogue** [comment]
Okay thanks those are some good ideas, I'll mull over the wording a bit more.
