### ISSUE TITLE
topspace empty lines vs real new lines

### ISSUE THREAD

**Issue by jdnavarro** [trevorpogue/topspace#7]
Is there a way to visually distinguish the topspace lines from actual leading new lines in the file itself?

Activating `indicate-empty-lines` only shows the bottom empty lines in the fringe.

**Comment by trevorpogue** [comment]
Yeah that's possible. Does this look okay to you?
![topspace-issue-#7](https://user-images.githubusercontent.com/12535207/159384934-2a992a57-4452-476c-9e29-23e7b85787a5.png)
I can't find a way to set the distinguisher character (~) to be _inside_ the left fringe/margin area though like it is with the bottom fringe, I tried a few things but it didn't work for more than one topspace line.

**Comment by jdnavarro** [comment]
That will work for me. Thanks for implementing it so quickly!

**Comment by trevorpogue** [comment]
Update: I figured out how to show the `topspace-empty-line-indicator` _inside_ the left fringe! (See #9)
![topspace-#9](https://user-images.githubusercontent.com/12535207/159794108-fddaaa7f-5764-4829-bcba-ddee1793ebda.png)

**Comment by jdnavarro** [comment]
Great! Now it's perfect.
